#pragma once

#include "utils.h"

void        module_register_function(const string_view& module, const string_view& symbol, const void*);
const void* module_symbol_lookup(const string_view& module, const string_view& symbol);

// Some DLL symbols are imported ordinal. As we dont load any OS dll's, we need to know what those ordinals
// actually refer to.
const char* module_ordinal_lookup(const string_view& module, uint16_t ordinal);

/*static Module modules[] = {
    {
        "COREDLL.dll", {
            { "__subs", nullptr },
            { "__muls", nullptr },
            { "__adds", nullptr },
            { "__lts", nullptr },
            { "__divs", nullptr },
            { "__stod", nullptr },
            { "atan", nullptr },
            { "__muld", nullptr },
            { "__dtos", nullptr },
            { "fclose", nullptr },
            { "fflush", nullptr },
            { "fwrite", nullptr },
            { "fread", nullptr },
            { "__led", nullptr },
            { "fprintf", nullptr },
            { "fopen", nullptr },
            { "sprintf", nullptr },
            { "atoi", nullptr },
            { "strstr", nullptr },
            { "fgetc", nullptr },
            { "strcpy", nullptr },
            { "__subd", nullptr },
            { "__eqs", nullptr },
            { "__itos", nullptr },
            { "__nes", nullptr },
            { "__gts", nullptr },
            { "__stoi", nullptr },
            { "memset", nullptr },
            { "__ged", nullptr },
            { "__divd", nullptr },
            { "__ltd", nullptr },
            { "__gtd", nullptr },
            { "rand", nullptr },
            { "__ned", nullptr },
            { "__les", nullptr },
            { "__addd", nullptr },
            { "__itod", nullptr },
            { "memcpy", nullptr },
            { "__ges", nullptr },
            { "strncpy", nullptr },
            { "__dtoi", nullptr },
            { "sqrt", nullptr },
            { "atan2", nullptr },
            { "strlen", nullptr },
            { "strcmp", nullptr },
            { "vsprintf", nullptr },
            { "fseek", nullptr },
            { "free", nullptr },
            { "malloc", nullptr },
            { "__rt_sdiv", nullptr },
            { "LocalFree", nullptr },
            { "FormatMessageW", nullptr },
            { "DeleteFileW", nullptr },
            { "CreateDirectoryW", nullptr },
            { "WideCharToMultiByte", nullptr },
            { "MultiByteToWideChar", nullptr },
            { "SetFilePointer", nullptr },
            { "CreateFileW", nullptr },
            { "WriteFile", nullptr },
            { "CloseHandle", nullptr },
            { "__rt_sdiv64by64", nullptr },
            { "sin", nullptr },
            { "cos", nullptr },
            { "tan", nullptr },
            { "__utod", nullptr },
            { "__utos", nullptr },
            { "floor", nullptr },
            { "ceil", nullptr },
            { "fabs", nullptr },
            { "__negs", nullptr },
            { "__negd", nullptr },
            { "__rt_udiv", nullptr },
            { "asin", nullptr },
            { "__stou", nullptr },
            { "__eqd", nullptr },
            { "UpdateWindow", nullptr },
            { "ShowWindow", nullptr },
            { "CreateWindowExW", nullptr },
            { "strncmp", nullptr },
            { "DefWindowProcW", nullptr },
            { "MessageBoxW", nullptr },
            { "PostQuitMessage", nullptr },
            { "DestroyWindow", nullptr },
            { "RegisterClassW", nullptr },
            { "LoadCursorW", nullptr },
            { "pow", nullptr },
            { "longjmp", nullptr },
            { "setjmp", nullptr },
            { "printf", nullptr },
            { "feof", nullptr },
            { "fscanf", nullptr },
            { "DispatchMessageW", nullptr },
            { "TranslateMessage", nullptr },
            { "PeekMessageW", nullptr },
            { "GetLastError", nullptr },
            { "GetProcAddressW", nullptr },
            { "LoadLibraryW", nullptr },
            { "sscanf", nullptr },
            { "swprintf", nullptr },
            { "atof", nullptr },
            { "waveOutReset", nullptr },
            { "waveOutClose", nullptr },
            { "waveOutUnprepareHeader", nullptr },
            { "waveOutPrepareHeader", nullptr },
            { "LocalAlloc", nullptr },
            { "waveOutOpen", nullptr },
            { "waveOutWrite", nullptr },
            { "ftell", nullptr },
            { "VirtualProtect", nullptr },
            { "GetVersionExW", nullptr },
            { "QueryPerformanceFrequency", nullptr },
            { "UnmapViewOfFile", nullptr },
            { "QueryPerformanceCounter", nullptr },
            { "Sleep", nullptr },
            { "GetMessageW", nullptr },
            { "MsgWaitForMultipleObjectsEx", nullptr },
            { "CreateEventW", nullptr },
            { "MapViewOfFile", nullptr },
            { "CreateFileMappingW", nullptr },
            { "SetForegroundWindow", nullptr },
            { "SetWindowPos", nullptr },
            { "GetWindowRect", nullptr },
            { "CreateDialogIndirectParamW", nullptr },
            { "LoadResource", nullptr },
            { "FindResourceW", nullptr },
            { "GlobalMemoryStatus", nullptr },
            { "_XcptFilter", nullptr },
            { "__C_specific_handler", nullptr }
        }
    },
    {
        "WS2.dll", {
            { "htonl",     nullptr },
            { "ntohs",     nullptr },
            { "bind",      nullptr },
            { "htons",     nullptr },
            { "ntohl",     nullptr },
            { "inet_addr", nullptr },
            { "inet_ntoa", nullptr }
        }
    },
    {
        "libgles_cm.dll", {
            { "eglGetConfigs", nullptr },
            { "eglQueryString", nullptr },
            { "eglInitialize", nullptr },
            { "eglGetDisplay", nullptr },
            { "glGetError", nullptr },
            { "glClientActiveTexture", nullptr },
            { "glActiveTexture", nullptr },
            { "glAlphaFunc", nullptr },
            { "glAlphaFuncx", nullptr },
            { "glBindTexture", nullptr },
            { "glBlendFunc", nullptr },
            { "glClear", nullptr },
            { "glClearColor", nullptr },
            { "glClearColorx", nullptr },
            { "glClearDepthf", nullptr },
            { "glClearDepthx", nullptr },
            { "glClearStencil", nullptr },
            { "glColorMask", nullptr },
            { "glColorPointer", nullptr },
            { "glCompressedTexImage2D", nullptr },
            { "glCompressedTexSubImage2D", nullptr },
            { "glCopyTexImage2D", nullptr },
            { "glCopyTexSubImage2D", nullptr },
            { "glCullFace", nullptr },
            { "glDeleteTextures", nullptr },
            { "glDepthFunc", nullptr },
            { "glDepthMask", nullptr },
            { "glDepthRangef", nullptr },
            { "glDepthRangex", nullptr },
            { "glDisable", nullptr },
            { "glDisableClientState", nullptr },
            { "glDrawArrays", nullptr },
            { "glDrawElements", nullptr },
            { "glEnable", nullptr },
            { "glEnableClientState", nullptr },
            { "glFinish", nullptr },
            { "glFlush", nullptr },
            { "glFrontFace", nullptr },
            { "eglChooseConfig", nullptr },
            { "glFrustumx", nullptr },
            { "glGenTextures", nullptr },
            { "glGetIntegerv", nullptr },
            { "glGetString", nullptr },
            { "glHint", nullptr },
            { "glLineWidth", nullptr },
            { "glLineWidthx", nullptr },
            { "glLoadIdentity", nullptr },
            { "glLoadMatrixf", nullptr },
            { "glLoadMatrixx", nullptr },
            { "glLogicOp", nullptr },
            { "glMatrixMode", nullptr },
            { "glNormalPointer", nullptr },
            { "glOrthof", nullptr },
            { "glOrthox", nullptr },
            { "glPopMatrix", nullptr },
            { "glPushMatrix", nullptr },
            { "glReadPixels", nullptr },
            { "glRotatef", nullptr },
            { "glRotatex", nullptr },
            { "glScalef", nullptr },
            { "glScalex", nullptr },
            { "glScissor", nullptr },
            { "glShadeModel", nullptr },
            { "glStencilFunc", nullptr },
            { "glStencilMask", nullptr },
            { "glStencilOp", nullptr },
            { "glTexCoordPointer", nullptr },
            { "glTexEnvf", nullptr },
            { "glTexImage2D", nullptr },
            { "glTexParameterf", nullptr },
            { "glTexSubImage2D", nullptr },
            { "glTranslatef", nullptr },
            { "glTranslatex", nullptr },
            { "glVertexPointer", nullptr },
            { "glViewport", nullptr },
            { "eglGetProcAddress", nullptr },
            { "eglCreateWindowSurface", nullptr },
            { "eglCreateContext", nullptr },
            { "eglGetConfigAttrib", nullptr },
            { "eglMakeCurrent", nullptr },
            { "eglDestroyContext", nullptr },
            { "eglDestroySurface", nullptr },
            { "eglTerminate", nullptr },
            { "glFrustumf", nullptr },
            { "eglGetError", nullptr },
            { "eglSwapBuffers", nullptr }
        }
    }
};*/
